app/urls.py
from django.urls import path
from . import views

urlpatterns = [

	path('register/', views.Register.as_view()),
	path('referrals/<mailId>', views.ReferralList.as_view()),
	path('status/<pk>', views.StatusList.as_view()),
	path('news/', views.NewsList.as_view()),
	path('top/contributers', views.RefreeList.as_view()),
	path('top/contributers', views.RefreeList.as_view()),
	path('top/nrc', views.TopNrcList.as_view()),	

	path('all/states/', views.StatesList.as_view()),
	path('all/division/', views.DivisionList.as_view()),
	path('all/district/', views.DistrictList.as_view()),
	path('all/nrc/', views.NrcList.as_view()),

	path('spec/division/<state>', views.CustomDivisionList.as_view()),
	path('spec/district/<state>', views.CustomDistrictList.as_view()),
	path('spec/nrc/<district>', views.CustomNrcList.as_view()),	


	path('nrc/referrals/', views.nrcReferrals),
	path('nrc/referrals/<pk>', views.updateStatus),
	path('accounts/register', views.register),
	path('nrc/register/patient', views.registerPatient),
	path('refer/', views.referPatient),
	
	path('', views.index),
	

]

sam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

app/forms.py
from django import forms
import json, requests
from .models import Nrc
from django.contrib.auth.models import User

class StatusUpdate(forms.Form):
	message = forms.CharField(label = 'Message', required = False)


	def clean(self):
		cleaned_data = super().clean()
		print(cleaned_data)



class RegisterForm(forms.Form):
	username = forms.CharField(label = 'Username')
	name = forms.CharField(label = 'Name')

	nrcCode = forms.CharField(label = 'NRC Code')
	email = forms.EmailField(label = 'E-mail')
	password1 = forms.CharField(label = 'Password', widget=forms.PasswordInput())
	password2 = forms.CharField(label = 'Confirm Password', widget=forms.PasswordInput())
	
	def clean(self):
		cleaned_data = super().clean()
		p1 = cleaned_data.get("password1")
		p2 = cleaned_data.get("password2")
		nrcCode = cleaned_data.get("nrcCode")
		username = cleaned_data.get("username")
		if len(User.objects.filter(username=username)) > 0:
			raise forms.ValidationError('Username already Exists')
		if len(p1) < 8:
			raise forms.ValidationError('Password should be minimum 8 characters long.')
		if p1 != p2:
			raise forms.ValidationError('Both Password fields should be same.')
		if len(Nrc.objects.filter(nrcCode = nrcCode)) == 0:
			raise forms.ValidationError('No NRC with this NRC Code.')
			

class RegisterPatientForm(forms.Form):
	childName = forms.CharField(label = 'Child Name')
	genderChoices = [('Male', 'Male'), ('Female', 'Female')]
	gender = forms.CharField(label = 'Gender', widget = forms.RadioSelect(choices = genderChoices))
	age = forms.IntegerField(label = 'Age (in months)')
	motherName = forms.CharField(label = "Mother's Name")
	fatherName = forms.CharField(label = "Father's Name")
	contactNo = forms.CharField(label = "Contact number")
	address = forms.CharField(label = "Address")
	tehsil = forms.CharField(label = "Tehsil / Block")
	def clean(self):
		cleaned_data = super().clean()
		contactNo = cleaned_data.get("contactNo")
		age = cleaned_data.get("age")
		if age < 1:
			raise forms.ValidationError('Invalid age')
		if len(contactNo) != 0 or not contactNo.isdigit():
			print('Enter a valid contact number')
			raise forms.ValidationError('Enter a valid contact number')
	
	
	
class ReferPatientForm(forms.Form):
	refreeMailId = forms.EmailField(label = 'Your E-mail Id')
	childName = forms.CharField(label = 'Child Name')
	genderChoices = [('Male', 'Male'), ('Female', 'Female')]
	gender = forms.CharField(label = 'Gender', widget = forms.RadioSelect(choices = genderChoices))
	age = forms.IntegerField(label = 'Age (in months)')
	motherName = forms.CharField(label = "Mother's Name")
	fatherName = forms.CharField(label = "Father's Name")
	contactNo = forms.CharField(label = "Contact number")
	address = forms.CharField(label = "Address")
	tehsil = forms.CharField(label = "Tehsil / Block")
	nrcCode = forms.CharField(label = 'NRC Code')
	
	

app/templates/base_generic.html
{% load static %}



<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
h1,h4{
      text-align: center;
      color:rgba(255,255,255,0.8);
      
    }
    h1{
      color:white;
      font-size:50px;
      margin-bottom:3px;
    }
    h4{
      margin-top:0px;
    }
    
    #buttons{
      text-align:center;
      margin-top:230px;
    }

    button.btn{
      border-radius:8px;
      padding:12px;
      transition: all 0.3s 0s linear;
      color:white;
      font-size:18px;
      width:150px;
    }
    button#reg{
      border:1px solid rgba(230,0,0,0.8);
      background-color: rgba(230,0,0,0.8);
      
    }
    button#log,button#ref{
      border:1px solid rgba(0,0,200,0.8);
      background-color: rgba(0,0,200,0.8);

    }
    button#log:hover{
      background-color:rgba(0,0,255,1);
      border-color:rgba(0,0,255,1)
    }
    button#ref:hover{
      background-color:rgba(0,0,255,1);
    }
    button#ref{
      width:200px;
}
    button#reg:hover{
      background-color: rgba(255,0,0,0.8);
    }
    span{
      color:white;
      font-size:24px; }
    
body {font-family: Arial, Helvetica, sans-serif;}

.navbar {
  width: 100%;
  background-color: white;
  float: left;
  overflow: auto;
}

.navbar a {
  float: right;
  padding: 12px;
  color: black;
  text-decoration: none;
  font-size: 17px;
}

.navbar a:hover {
  background-color: #000;
  color: white;
}

.active {
  background-color: #4CAF50;
}

@media screen and (max-width: 500px) {
  .navbar a {
    float: none;
    display: block;
  }
}

table {

  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;

}

​

th, td {

  text-align: left;

  padding: 8px;

}
body {
  font-family: Arial, Helvetica, sans-serif;
  
}


/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password], input[type=email], input[type = number]{
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus, input[type=email], input[type = radio], input[type = number] {
  background-color: #ddd;
  outline: none;
}


/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */


/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
​

tr:nth-child(even){background-color: #f2f2f2}
   .submit{
    border-radius: 4px;
    transition: all 0.3s 0s linear; 
    padding:6px;
    }

    #sub.submit{
    border:1px solid blue;
    background-color: white;
    }
    #mark.submit{
    border:1px solid red;
    background-color:rgba(230,0,0,0.7);
    color:white;
    }
    #approve.submit{
    border:1px solid rgba(50,230,100,0.7);
    background-color:rgba(50,230,100,0.7);
    color:white;
    }
    #sub.submit:hover{
    background-color:rgba(0,0,230,0.7);
    color:white;
    }
    #mark.submit:hover{
     background-color:red;  
    }
    #approve.submit:hover{
    background-color:rgba(0,230,0);
    }
div.container{
    width:1100px;
    margin:auto;
}
input[name="message"]{
    border:1px solid #777;
    box-shadow:1px 0.6px 1px 1px #777;
    background-color:white;
    border-radius:3px;
    width:1050px;
}
input[name="message"]:focus{
    background-color:white;
    border:1px solid blue;
}
.tag{
    background-color:rgba(180,0,0,0.7);
    padding:10px;
    padding-top:15px;
    color:white;

}
#buttons{
    text-align:center;
}
table,th,td{
    border:1px solid #777;
}
a{
    transition:all 0.3s 0s linear;
}
a:hover{
    background-color:rgba(230,0,0,0.7);
}
#reg_form{
  width:600px;
  margin:auto;
  border-top-left-radius: 7px;
  border-bottom-right-radius: 7px;
  box-shadow: 4px 4px 2px #777;
  
}
input#id_username[name="username"],input#id_password[name="password"]{
  width:300px;
}
input[name="message"]#id_message{
  transition: all 1s 0s linear;
}
input[name="message"]#id_message:focus{
  width:1000px;
}
h4{
  background-color: none;
}
form input[type="text"],form input[type="number"],form input[type="email"],input[type="password"]{
  border-radius: 5px;
  border:1px solid black;
  background:transparent;
  width:550px;
}
div#buttons{
  margin-top:20px;
}
label{
  display:block;
}
   div form#reg_form{
      width:1100px !important;
    }
{% block css %}
{% endblock %}
</style>

	{% block title %}
	<title>Title</title>
	{% endblock %}
	<!-- Google font -->
	{% block link %}
	{% endblock %}
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round" rel="stylesheet">
</head>

<body>


<div class="navbar">
		{% block nav %}
  <a class="active" href="#"><i class="fa fa-fw fa-home"></i> Home</a> 
  <a href="#"><i class="fa fa-fw fa-search"></i> Search</a> 
  <a href="#"><i class="fa fa-fw fa-envelope"></i> Contact</a> 
  <a href="#"><i class="fa fa-fw fa-user"></i> Login</a>
  		{% endblock %}

</div>

	{% block content %}	

	{% endblock %}

</body>

</html>

app/templates/index.html
{% load static %}
<html>
<head>
	<title>AAROGYA</title>
	<style>
		h1,h4{
			text-align: center;
			color:rgba(255,255,255,0.8);
			
		}
		h1{
			color:white;
			font-size:50px;
			margin-bottom:3px;
		}
		h4{
			margin-top:0px;
		}
		
		#buttons{
			text-align:center;
			margin-top:230px;
		}

		button.btn{
			border-radius:8px;
			padding:12px;
			transition: all 0.3s 0s linear;
			color:white;
			font-size:18px;
			width:150px;
		}
		button#reg{
			border:1px solid rgba(230,0,0,0.8);
			background-color: rgba(230,0,0,0.8);
			
		}
		button#log,button#ref{
			border:1px solid rgba(0,0,200,0.8);
			background-color: rgba(0,0,200,0.8);

		}
		button#log:hover{
			background-color:rgba(0,0,255,1);
			border-color:rgba(0,0,255,1)
		}
		button#ref:hover{
			background-color:rgba(0,0,255,1);
		}
		button#ref{
			width:200px;
}
		button#reg:hover{
			background-color: rgba(255,0,0,0.8);
		}
		span{
			color:white;
			font-size:24px;	}
		
		body{
			background-image: url("{% static 'samlogo.jpg' %}");
		}
	</style>
</head>
<body>
	<section>
		<h1>42% of India's children are malnourished</h1>
		<h4>They cannot go to school, work, or aspire. 1500 of our future doctors, engineers or sportsmen are dying - every day</h4>
	</section>
	<section id="buttons">
	
		<a href="http://127.0.0.1:8000/accounts/register"><button type="button" class="btn" id="reg"> Register </button></a>
		<a href="{% url 'login'%}"><button type="button" class="btn" id="log">Login</button></a>
		<br/><br/>
		<span>OR</span>
		<br/><br/>
		<a href="http://127.0.0.1:8000/refer"><button type="button" class="btn" id="ref">Refer Child</button></a></section>
</body>
</html>

app/templates/nrcReferrals.html
{% extends "base_generic.html" %}
{% block title %}
<title> {{user.username}} | Referrals </title>
{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1">

{% block nav %}
<a href="{% url 'logout'%}"><i class="fa fa-fw fa-user"></i>Logout</a>
{% endblock %}




{% block content %}

    {% if nrc %}
        <h1 class="head">{{nrc.nrcName}}</h1>
    {% endif %}
    {% if msg %}
    <h1> {{msg}} </h5>
    {% endif %}


    	{% if referrals %}
        <div style="overflow-x:auto;">
            <table>
                <tr >
                    <th> # </th>
                    <th> Child Name</th>
                    <th> Father's Name</th>
                    <th> Mother's Name</th>
                    <th> Block/Tehsil/City </th>
                    <th> Contact No. </th>
                    <th> Referral Created At </th>
                    <th> Update Status</th>
                </tr>
                {% for referral in referrals %}
                <tr>
                    <td> {{referral.pk}} </td>
                    <td> {{referral.childName}}</td>
                    <td> {{referral.fatherName}} </td>
                    <td> {{referral.motherName}}  </td>
                    <td> {{referral.tehsil}} </td>
                    <td> {{referral.contactNo}} </td>
                    <td> {{referral.createdAt}} </td>
                    <td><a href="http://127.0.0.1:8000/nrc/referrals/{{ referral.pk}}"><button type="button" style="border:1px solid rgba(200,0,0,0.8);background-color: red;padding:6px;border-radius: 4px;color:white">Update Status</button></a></td>
                    </tr>
                {% endfor %}
                
            </table>
        </div>

        {% endif %}
{% endblock %}

app/templates/referPatient.html
{% extends "base_generic.html" %}
{% block title %}
<title> Refer Patient </title>
{% endblock %}


{% block css %}
 
{% endblock %}




{% block nav %}
<a href="http://127.0.0.1:8000/"><i class="fa fa-fw fa-home"></i> Home </a>
<a href="{% url 'logout'%}"><i class="fa fa-fw fa-user"></i>Logout</a>

{% endblock %}

{% block content %}
<div class="container">
{% if error %}
<h1> {{error}} </h1>
{% endif %}

{% if msg %}
<h1> {{msg}} </h1>
{% endif %}



<form method = "POST" id="refer_form">
	{% if form %}
	<br><br>
	<h4 class="tag">Reffer Patient</h4>
	{% csrf_token %}
	
	{{ form }}
    <div id="buttons">
	<button type = "submit" class="submit" id="sub"> Submit </button>
    {% endif %}

</form>
</div>
{% endblock %}

app/templates/register.html
{% extends "base_generic.html" %}



{% block title %}
<title>Register</title>
{% endblock %}





{% block nav %}
<a href="{% url 'login'%}"><i class="fa fa-fw fa-user"></i>Login</a>
{% endblock %}

	{% block content %}
	<div >
	<form method="POST" id="reg_form">
		{% csrf_token %}
		{{form}}
	<button type="submit" class="main-btn submit" id="sub">Submit</button>
	</form>
</div>
	{% endblock %}

</body>
</html>

app/templates/registerPatient.html
{% extends "base_generic.html" %}
{% block title %}
<title> Register Patient </title>
{% endblock %}


{% block css %}
 
{% endblock %}




{% block nav %}
<a href="{% url 'logout'%}"><i class="fa fa-fw fa-user"></i>Logout</a>
{% endblock %}

{% block content %}
<div class="container">
{% if error %}
<h1> {{error}} </h1>
{% endif %}

{% if msg %}
<h1> {{msg}} </h1>
{% endif %}



<form method = "POST">
	{% if form %}
	<br><br>
	<h4 class="tag">Register Patient</h4>
	{% csrf_token %}
	
	{{ form }}
    <div id="buttons">
	<button type = "submit" class="submit" id="sub"> Submit </button>
    {% endif %}

</form>
</div>
{% endblock %}

app/templates/updateStatus.html
{% extends "base_generic.html" %}
{% block title %}
<title> Status | {{pk}} </title>
{% endblock %}


{% block css %}
 
{% endblock %}




{% block nav %}
<a href="{% url 'logout'%}"><i class="fa fa-fw fa-user"></i>Logout</a>
{% endblock %}

{% block content %}
<div class="container">
{% if error %}
<h1> {{error}} </h1>
{% endif %}
{% if statusList %}

    <h2 class="tag"> Status for {{child}} </h2>

    <div style="overflow-x:auto;">
            <table>
                <tr >
                    <th> Created At </th>
                    <th> Message</th>
                    <th> Updated By</th>
                </tr>
                {% for status in statusList %}
                <tr>
                    <td> {{status.createdAt}} </td>
                    <td> {{status.message}} </td>
                    <td> {{status.updatedby.username}} </td>
                </tr>
                {% endfor %}
                
            </table>


{% endif %}

<form method = "POST">
	{% if form %}
	<br><br>
	<h4 class="tag">Update Status</h4>
	{% csrf_token %}
	
	{{ form }}
    <div id="buttons">
	<button type = "submit" class="submit" id="sub"> Submit </button>
    {% endif %}
{% if name1 %}
    <input type="submit" name="{{val1}}" value="{{name1}}" class="submit" id="mark">
{% endif %}
{% if name2 %}
    <br/><br/>
    <input type="submit" name="{{val2}}" value="{{name2}}" class="submit" id="approve">
</div>
{% endif %}



</form>
</div>
{% endblock %}